### ISSUE TITLE
King can still move to spaces where it remains in check

### ISSUE THREAD

**Issue by Can1Cyp2** [jordanlandry/chess-with-minimax#1]
In certain instances when the king is in check, it can move to a position where the king is still or again put in check. 

### For example:
![King](https://user-images.githubusercontent.com/93102902/211091681-ebff8e25-be41-49bd-961e-d9660efc13ba.PNG)
In this photo, the king was where the queen was. It was originally one square lower, beside the pawn. I should not have been able to move up. I should have only been able to move to the top right square, because then I would be out of check.

**Comment by jordanlandry** [comment]
yea ik

**Comment by Can1Cyp2** [comment]
please fix, thank

**Comment by jordanlandry** [comment]
Fixed with most recent push
